// ===== import components =====
import BottomBar from "@/components/layout/bottomBar/BottomBar";
import Header from "@/components/layout/header/Header";
import Sidebar from "@/components/layout/sidebar/Sidebar";

// ===== css styles =====
import "@/styles/globals.css";
import "@/styles/style.css";

// ===== font styles =====
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// ===== seo metadata =====
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-muted-100 dark:bg-muted-900">
          <Header />
          <Sidebar />
          <div className="bg-muted-100 dark:bg-muted-900 dark:text-white relative min-h-screen w-full overflow-x-hidden transition-all duration-300 px-4 lg:px-10 lg:max-w-[calc(100%_-_80px)] lg:ms-[80px]">
            {children}
          </div>
          <BottomBar />
        </main>
      </body>
    </html>
  );
}
