// ===== css styles =====
import "@/styles/globals.css";
import "@/styles/style.css";

// ===== font styles =====
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// ===== seo metadata =====
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-muted-100 dark:bg-muted-900">{children}</main>
      </body>
    </html>
  );
}
